### ISSUE TITLE
bin/keynanny needs a proper usage message

### ISSUE THREAD

**Issue by aleibl** [certnanny/KeyNanny#37]
Line 29:

sub usage {
    print "Usage: ...\n";
}

**Comment by mbartosch** [comment]
It already has one:
keynanny --help
prints the usage section.

The sub usage() is bogus and simply needs to be removed, the call to usage() needs to be replaced with
pod2usage(
    {
        -exitval => 1,
        -verbose => 0,
    } )

(Sorry, I cannot fix this myself currently.)

**Comment by mbartosch** [comment]
resolved in b82674e
